#!/bin/bash

case $1 in
	"-py")
		output=$(tuxi -q -r $2 | tr -d "\n" | tr -s '[:blank:]' '+')
		;;
	"-err")
		output="Sorry+I+didnt+get+that"
		;;
esac
#output=${output// /+}
#mkdir -p /tmp/piri
curl "http://www.google.com/speech-api/v1/synthesize?lang=en-us&text=$output" --output /tmp/piri/reply.mp3 && ffplay -nodisp -autoexit /tmp/piri/reply.mp3 >/dev/null 2>&1
